### ISSUE TITLE
Support for freemarker <> syntax as optional setting

### ISSUE THREAD

**Issue by bennettfrazier** [fentech/freemarker-magnolia-snippets#4]
Adding syntax support for html tags like `<#if argument>` vs the default `[#if argument]` as an optional setting would be a handy feature!

**Comment by fentech** [comment]
I'll try to get this in as soon as I can!

**Comment by fentech** [comment]
@bennettfrazier I made the changes. I'll get them published when I get home.

**Comment by bennettfrazier** [comment]
@fentech sweet thanks!

**Comment by fentech** [comment]
It was just published. Should be available here in a little bit!
